#!/usr/bin/env ruby

require "rubygems"
require "treetop"

# expand search path correct subdir.
$: << File.expand_path(File.dirname(__FILE__))

require "lib/core"
require "pp"
require "evaluator"

# parser nodes
Dir.glob("parser/nodes/*.rb").each{ |f| require f }

# load grammar
Treetop.load "grammar/blockd.tt"

#require "grammar/blockd"


if ARGV.size < 1
  raise "Error: Please specify a source file to interpret."
end


parse_file = ARGV[0]
parser = BlockdParser.new
ast = parser.parse IO.read(parse_file)

# start evaluation process
ast.evaluate

debug_on =  ARGV.include?("--debug")
ruby_output = ARGV.include?("--ruby")

if debug_on
  puts ast.inspect
  puts "\n============================================================\n\n"
  puts "--------------------\n"
  puts "Generated Ruby code:\n"
  puts "--------------------\n\n"
  Evaluator.inspect
  puts "\n============================================================\n\n"
end


if ruby_output
  Evaluator.inspect
else
  Evaluator.eval

  if debug_on
    puts
  end
end

